#!/usr/bin/env bash

set -eo pipefail

indent() {
  sed "s/^/       /"
}

puts-step() {
  echo "-----> $*"
}

puts-warn() {
  echo " !     $*"
}


# Set graphviz path
export PATH=${BUILD_DIR}/heroku-buildpack-graphviz/usr/bin:${PATH}
export GRAPHVIZ_DOT=${BUILD_DIR}/heroku-buildpack-graphviz/usr/bin/dot
export LD_LIBRARY_PATH=${BUILD_DIR}/heroku-buildpack-graphviz/usr/lib:${BUILD_DIR}/.heroku/vendor/lib/:${LD_LIBRARY_PATH}

puts-step "Setting up Sphinx environment"

# All requirements of wsgi.py
pip install -q static | indent

# Needed to serve the application (Procfile)
pip install -q waitress | indent

pip install -q Sphinx | indent

# Get sphinx build-dir
echo -e "\necho-build-dir:\n\t@echo '\$(BUILDDIR)'\n" >> ${BUILD_DIR}/Makefile
(cd ${BUILD_DIR} && make echo-build-dir > ${BUILD_DIR}/.build-dir)

puts-step "Build Sphinx docs"

# Build Sphinx documentation
(cd ${BUILD_DIR} && make html) | indent
